package Interfáz;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author franco
 */
public class Tiebreack extends javax.swing.JFrame {


    static int prueba;
    
    public Tiebreack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDeuce = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTieBreack = new javax.swing.JLabel();

        jDeuce.setFont(new java.awt.Font("Ubuntu Medium", 0, 24)); // NOI18N
        jDeuce.setText("40                        -                        15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Miranda");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 47, 56, 17);

        jLabel2.setText("Pinke");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 47, 38, 17);

        jRadioButton1.setText("Punto jugador 1");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(12, 139, 135, 24);

        jRadioButton2.setText("Punto jugador 2");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(253, 139, 135, 24);

        jTieBreack.setFont(new java.awt.Font("Ubuntu Medium", 0, 24)); // NOI18N
        jTieBreack.setText("40                      -                        15");
        getContentPane().add(jTieBreack);
        jTieBreack.setBounds(40, 230, 340, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tiebreack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tiebreack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDeuce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel jTieBreack;
    // End of variables declaration//GEN-END:variables
}
